database:
  url: 'postgresql+asyncpg://masaryk:changeit@localhost:9432/discord'
  echo: true

redis:
  url: 'redis://localhost:9379'

bot:
  prefix: '!'

  cogs:
    sync:
      guilds:
        - 573528762843660299