!Config
bot: !bots
    prefix: '!'
    DEBUG: false

emoji: !emojis
    Verification: 605131658219356170

colors: !colors
    MUNI_YELLOW: 15387993

guilds:
- !guilds
    id: 486184376544002073
    name: fi_muni

    channels: !channels
        verification: 621365818034356224
        about_you: 621365826372632606
        course: !course
            MINIMUM_REGISTRATIONS: 10
            registration_channel: 628684083345489950
        threaded:
        - 988839106656215041
        starboard: !starboard
            REACT_LIMIT: 10
            starboard: 1041587227748212776
            best_of_masaryk: 930957842356244530
            best_of_memes: 836224046030520410
            channels: !starch
                ignored:
                - 988839106656215041
                - 625263765100953612
                - 621718588478324736
                - 504953215385600011
                - 609086101511995422
                penalised:
                - 5041 9443 0560 1085 55    
            emojis: !starem
                ignored: []
                penalised: []

    cogs: !cogs
        markov: !markov
            context_size: 6

    logs: !logs
        errors: 609413180137144331
        mute: null
        other: null
        webhook: null

    roles: !roles
        muted: 627901278365810698
        verified: 621304939502632960
        moderator: null
        admin: 504237720965480450
        show_all: 628684833039712266

- !guilds
    id: 573528762843660299
    name: fi test

    channels: !channels
        verification: 731525269214724116
        about_you: 760211019405590540
        course: !course
            MINIMUM_REGISTRATIONS: 1
            registration_channel: 758267743119212576
        threaded:
            - 988918829570744350
        starboard: !starboard
            REACT_LIMIT: 1
            starboard: 751062312781217792
            best_of_memes: null
            best_of_masaryk: 930952840703262744
            channels: !starch
                ignored:
                    - 988918829570744350
                penalised:
                    - memes
            emojis: !starem
                ignored:
                    - .*_wine
                penalised:
                    - kek|pepe|lul|lol|pog|peepo|ano|nie|yes|no|cringe

    cogs: !cogs
        markov: !markov
            context_size: 6

    logs: !logs
        errors: 731435447787716680
        mute: 731435469472006156
        other: 731435447787716680
        webhook: https://discord.com/api/webhooks/816237455913123870/9H7BGuwt6nQi_jDa3wwGf9yZuqaUvQCXJQpM4iz_IEvKavH5hRIf_rP6ejmfqqJ6gXZS

    roles: !roles
        muted: null
        verified: 740961005961609328
        moderator: 627249759694094366
        admin: 573595915302993920
        show_all: 760093273871613993
