version: '3.8'

services:
  database:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=masaryk
      - POSTGRES_PASSWORD=localdbpassword
      - POSTGRES_DB=discord
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data     # persist data even if container shuts down

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - .:/MasarykBOT
    env_file: .env
    depends_on:
      - database

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    volumes:
      - .:/MasarykBOT
    environment:
      - POSTGRES=postgresql://masaryk:localdbpassword@database/discord
    depends_on:
      - database



volumes:
  postgres: