version: '3.8'

services:
  database:
    container_name: db
    build:
      context: database/
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    env_file:
      - database/.env
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data     # persist data even if container shuts down
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
      - .:/MasarykBOT
    env_file: .env
    network_mode: host
    depends_on:
      - database



volumes:
  postgres: