version: '3.8'

services:
  database:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - database/.env
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data     # persist data even if container shuts down
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot/Dockerfile.bot
    volumes:
      - .:/MasarykBOT
    env_file: .env
    depends_on:
      - database



volumes:
  postgres: