version: '3.8'

services:
  database:
    container_name: bot.db
    image: postgres:13
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_USER=masaryk
      - POSTGRES_PASSWORD=localdbpassword
      - POSTGRES_DB=discord
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data     # persist data even if container shuts down
    restart: unless-stopped

  bot:
    container_name: bot.bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - COLUMNS=150
    volumes:
      - .:/MasarykBOT
    depends_on:
      - database
    restart: unless-stopped

  tests:
    container_name: bot.tests
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    volumes:
      - .:/MasarykBOT
    profiles:
      - test

  database_backup:
    container_name: bot.db_backup
    image: prodrigestivill/postgres-backup-local
    volumes:
      - ./database/backup:/backups
    links:
      - database
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=masaryk
      - POSTGRES_PASSWORD=localdbpassword
      - POSTGRES_DB=discord
      - POSTGRES_EXTRA_OPTS=-Z6 --blobs
      - SCHEDULE=@daily
    restart: unless-stopped
    profiles:
      - prod

volumes:
  postgres:
