version: '3.8'

services:
  environment:
    container_name: bot_environment
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/MasarykBOT
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      - database


